// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpybvDBqwvLnKaWJwBmTgyGBghGTT7_gY',
    appId: '1:783897051932:android:120d0550e49b87b3ec30d9',
    messagingSenderId: '783897051932',
    projectId: 'kickchain-app',
    storageBucket: 'kickchain-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhrzqPNdtENdNAbaPkGOuVNQj55PJOiE',
    appId: '1:783897051932:ios:9438bd98cfaba990ec30d9',
    messagingSenderId: '783897051932',
    projectId: 'kickchain-app',
    storageBucket: 'kickchain-app.firebasestorage.app',
    iosBundleId: 'com.kickchain.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6QVH4ss4_a6Hh7eD3in36YJ5D_okO4o',
    appId: '1:783897051932:web:29aaa8e11efa2e62ec30d9',
    messagingSenderId: '783897051932',
    projectId: 'kickchain-app',
    authDomain: 'kickchain-app.firebaseapp.com',
    storageBucket: 'kickchain-app.firebasestorage.app',
    measurementId: 'G-TK4HZ446X7',
  );

}